name: Testing
run-name: ${{ github.actor }} is running the Tests
on:
  push:
    paths:
      - '**'  # Trigger the workflow on any push
      
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: |
          if [[ ! "$(git diff --name-only ${{ github.sha }}^..${{ github.sha }})" =~ ^landing-page/ ]]; then
            npm run test
          else
            echo "Skipping tests for changes within 'landing-page' directory."
          fi

